import fonts from './pdf-fonts.json' with {type:'json'};
// One-page PDF using built-in Helvetica and WinAnsi; compatible with Workers.
function pdfText(value:string){return value.normalize('NFC').replace(/[\u2013\u2014]/g,'-').replace(/[^\x20-\xFF]/g,'').replace(/[\\()]/g,'\\$&');}
function wrap(text:string,max=85){const words=text.split(/\s+/),lines:string[]=[];let line='';for(const word of words){if((line+' '+word).length>max&&line){lines.push(line);line=word}else line+=(line?' ':'')+word;}if(line)lines.push(line);return lines;}
export function proposalPdf(id:string,d:any,r:any,date:string){let content='';function rect(x:number,y:number,w:number,h:number,color:string){content+=`${color} rg ${x} ${y} ${w} ${h} re f\n`;}
function text(x:number,y:number,value:string,size=11,bold=false,color='0.03 0.11 0.28'){content+=`BT /${bold?'F2':'F1'} ${size} Tf ${color} rg 1 0 0 1 ${x} ${y} Tm (${pdfText(value)}) Tj ET\n`;}
const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});const num=(n:number)=>n.toLocaleString('pt-BR',{maximumFractionDigits:2});
rect(0,725,595,117,'0.025 0.11 0.28');text(40,793,'Renovo',29,true,'1 1 1');text(40,772,'ENERGIA SOLAR',10,false,'1 1 1');text(40,745,'PRÉ-PROPOSTA DE ENERGIA SOLAR',14,true,'1 0.5 0.1');text(380,792,id,12,true,'1 1 1');text(380,772,new Date(date).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'}),10,false,'1 1 1');
let y=698;text(40,y,'DADOS DO CLIENTE',12,true);y-=23;for(const line of [`Nome: ${d.nome}`,`WhatsApp: ${d.whatsapp}${d.email?' | E-mail: '+d.email:''}`,`Localização: ${d.cidade}/${d.estado} | CEP: ${d.cep}`,`Imóvel: ${d.tipo_imovel} | Condição: ${d.imovel_proprio}`,`Instalação: ${d.tipo_telhado}`]){for(const l of wrap(line)){text(40,y,l);y-=16;}}
y-=15;rect(40,y-77,515,93,'0.94 0.96 0.98');text(55,y-5,'INVESTIMENTO ESTIMADO',10,true);text(55,y-39,money(r.cost??r.min),28,true,'0.85 0.28 0');text(330,y-5,'SISTEMA RECOMENDADO',10,true);text(330,y-39,`${r.modules} placas solares`,20,true);y-=110;text(40,y,'RESUMO DO SISTEMA',12,true);y-=22;
for(const [label,value] of [['Conta de energia atual',money(d.valor_conta)+'/mês'],['Consumo mensal estimado',num(r.consumption)+' kWh'],['Geração mensal estimada',num(r.generation)+' kWh'],['Geração anual estimada',num(r.annualGeneration)+' kWh'],['Potência estimada do sistema',num(r.kwp)+' kWp'],['Economia mensal estimada',money(r.savings)],['Economia anual estimada',money(r.annualSavings)],['Economia acumulada em '+r.years+' anos',money(r.accumulated)],['Retorno simples estimado',num(r.payback)+' anos']]){text(40,y,label);text(330,y,value,11,true);y-=21;}
y-=8;text(40,y,'EQUIPAMENTOS E MATERIAIS',12,true);y-=22;for(const line of [`${r.modules} placas solares`,`${r.inverters||1} inversor(es) - dimensionamento sujeito à avaliação técnica`,'Estrutura em alumínio','Cabos solares com proteção UVA e UVB']){text(40,y,line);y-=18;}
y-=14;for(const line of wrap('Pré-proposta estimativa, sujeita à análise técnica do imóvel, tarifa de energia e condições de instalação. A proposta oficial será confirmada pela equipe da Renovo no WhatsApp.',90)){text(40,y,line,10,false,'0.4 0.45 0.52');y-=14;}text(40,43,'Renovo Energia Solar | WhatsApp (15) 99169-9585',10,true);text(40,27,'Documento gerado pelo simulador do site. Guarde seu código para o atendimento.',9,false,'0.4 0.45 0.52');
const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>',`<< /Type /Font /Subtype /TrueType /BaseFont /LiberationSans /Encoding /WinAnsiEncoding /FirstChar 32 /LastChar 255 /Widths [${fonts.regular.widths.join(' ')}] /FontDescriptor 7 0 R >>`,`<< /Type /Font /Subtype /TrueType /BaseFont /LiberationSans-Bold /Encoding /WinAnsiEncoding /FirstChar 32 /LastChar 255 /Widths [${fonts.bold.widths.join(' ')}] /FontDescriptor 9 0 R >>`,`<< /Length ${content.length} >>\nstream\n${content}endstream`];for(const [i,key] of ['regular','bold'].entries()){const font=(fonts as any)[key];const fontBytes=atob(font.base64);objects.push(`<< /Type /FontDescriptor /FontName /${i?'LiberationSans-Bold':'LiberationSans'} /Flags 32 /FontBBox [${font.bbox.join(' ')}] /ItalicAngle 0 /Ascent ${font.ascent} /Descent ${font.descent} /CapHeight 687 /StemV ${i?120:80} /FontFile2 ${i?10:8} 0 R >>`,`<< /Length ${fontBytes.length} /Length1 ${fontBytes.length} >>\nstream\n${fontBytes}\nendstream`);}let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;});const start=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`+offsets.slice(1).map(x=>String(x).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;return Uint8Array.from(pdf,c=>c.charCodeAt(0));}
