import {database} from './database.js';
import {requestContext,verifySession} from './auth.js';
import {defaults} from './calculator.js';
export function runtime():any{return process.env;}
export function db():any{return database;}
export async function config(){const r=await db().prepare('SELECT data FROM calculator_settings WHERE id = ?').bind('main').first();const stored=r?JSON.parse(r.data):{};return {...defaults,...stored,whatsapp:runtime().RENOVO_WHATSAPP||stored.whatsapp||defaults.whatsapp};}
export async function admin(){const req=requestContext.getStore();if(!req||!verifySession(req))throw Error('Acesso administrativo não autorizado.');return {role:'admin'};}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(origin && origin!==new URL(req.url).origin)throw Error('Origem inválida.');}
export function fail(e:any,status=400){return Response.json({error:e.message || 'Não foi possível concluir. Tente novamente.'},{status});}
export async function limit(req:Request){const ip=req.headers.get('x-forwarded-for')?.split(',')[0].trim()||'local';const minute=Math.floor(Date.now()/60000);const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ip));const key=Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,'0')).join('')+minute;const r=await db().prepare('INSERT INTO rate_limits(id,count,expires) VALUES(?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count').bind(key,Date.now()+120000).first();if(r.count>12)throw Error('Muitas tentativas. Aguarde um minuto.');await db().prepare('DELETE FROM rate_limits WHERE expires < ?').bind(Date.now()).run();}
export async function deliver(id:string){const row=await db().prepare('SELECT * FROM webhook_outbox WHERE id=?').bind(id).first();if(!row||row.status==='sent')return;const s=await config();const url=runtime().N8N_WEBHOOK_URL||s.webhook;if(!url)return;const u=new URL(url);if(u.protocol!=='https:'||/^(localhost|127\.|10\.|192\.168\.|169\.254\.)/.test(u.hostname))throw Error('Webhook deve usar HTTPS público.');try{const response=await fetch(url,{method:'POST',redirect:'manual',headers:{'Content-Type':'application/json','Idempotency-Key':id,...(runtime().N8N_WEBHOOK_SECRET?{'Authorization':'Bearer '+runtime().N8N_WEBHOOK_SECRET}:{})},body:row.payload,signal:AbortSignal.timeout(8000)});if(!response.ok)throw Error('Webhook recusou a entrega');await db().prepare('UPDATE webhook_outbox SET status=?,attempts=attempts+1,updated=? WHERE id=?').bind('sent',new Date().toISOString(),id).run();}catch(e:any){console.error('Webhook delivery failed:',e.message);await db().prepare('UPDATE webhook_outbox SET status=?,attempts=attempts+1,updated=? WHERE id=?').bind('pending',new Date().toISOString(),id).run();}}
